name: package-integrity

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  ncurses:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: ./diy.sh build ncurses
